import { createElement } from 'lwc';
import Convocation_Stagaire_Button from 'c/convocation_Stagaire_Button';

describe('c-convocation-stagaire-button', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-convocation-stagaire-button', {
            is: Convocation_Stagaire_Button
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});